
services:
  coredns_gslb:
    container_name: coredns_gslb
    image: dmachard/coredns_gslb:${COREDNS_GSLB_VERSION:-latest}
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
      - "9153:9153/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./Dockerfile:/Dockerfile
      - ./tests/db.gslb.example.com:/db.gslb.example.com
      - ./tests/appX_records.yml:/coredns/appX_records.yml
      - ./tests/appY_records.yml:/coredns/appY_records.yml
      - ./tests/location_map.yml:/coredns/location_map.yml
      - ./tests/GeoLite2-Country.mmdb:/coredns/GeoLite2-Country.mmdb
      - ./tests/GeoLite2-City.mmdb:/coredns/GeoLite2-City.mmdb
      - ./tests/GeoLite2-ASN.mmdb:/coredns/GeoLite2-ASN.mmdb
    command: -conf /Corefile
    env_file:
      - docker-example.env
    restart: always