
services:
  coredns_gslb:
    container_name: coredns_gslb
    image: dmachard/coredns_gslb:${COREDNS_GSLB_VERSION:-latest}
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
      - "9153:9153/tcp"
    volumes:
      - ./coredns/Corefile:/Corefile
      - ./coredns/db.gslb.example.com:/db.gslb.example.com
      - ./coredns/gslb_config.example.com.yml:/gslb_config.example.com.yml
      - ./coredns/location_map.yml:/coredns/location_map.yml
      - ./coredns/GeoLite2-Country.mmdb:/coredns/GeoLite2-Country.mmdb
      - ./coredns/GeoLite2-City.mmdb:/coredns/GeoLite2-City.mmdb
      - ./coredns/GeoLite2-ASN.mmdb:/coredns/GeoLite2-ASN.mmdb
      - ./coredns/healthcheck_custom.sh:/coredns/healthcheck_custom.sh:ro
    command: -conf /Corefile
    env_file:
      - docker-example.env
    restart: always