name: Go Cross-Platform Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/386]

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          PLATFORM=${{ matrix.platform }}  
          TAG=$(echo "$PLATFORM" | tr '/' '-')
          docker build --platform $PLATFORM --file ./Dockerfile -t coredns_gslb:$TAG .