name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  COREDNS_VERSION: "1.12.2"
  GO_VERSION: "1.23"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Checkout coredns
        uses: actions/checkout@v4
        with:
          repository: coredns/coredns
          ref: v${{ env.COREDNS_VERSION }}
          path: coredns
      
      - name: Checkout gslb plugin
        uses: actions/checkout@v4
        with:
          path: coredns-gslb
      
      - name: Copy plugin to coredns directory
        run: |
          cp -r coredns-gslb coredns/plugin/gslb
      
      - name: Build release binary
        run: |
          set -x -e
          cd coredns
          # Add plugin to plugin.cfg with local path
          sed -i '/file:file/i gslb:gslb' plugin.cfg
          # Add replace directive for local plugin
          go mod edit -replace github.com/coredns/coredns/plugin/gslb=./plugin/gslb
          go mod tidy
          go generate
          make -f Makefile.release release -e LINUX_ARCH="amd64 arm64" VERSION=${{ github.ref_name }}
      
      
      - name: Build release binary sha256
        run: |
          cd coredns/release
          for asset in *.tgz; do 
            sha256sum "$asset" > "$asset.sha256"
          done
      
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            coredns/release/*.tgz
            coredns/release/*.tgz.sha256