name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

env:
  GOLANGCI_LINT_VERSION: "v2.1.6"

jobs:
  testunits:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        go-version: ['1.23', '1.24']
        
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        # workaround: when the files to be extracted are already present, 
        # tar extraction in Golangci Lint fails with the "File exists"
        # https://github.com/golangci/golangci-lint-action/issues/807
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: "${{ env.GOLANGCI_LINT_VERSION }}"
        args: --timeout 3m --verbose

    - name: Test
      run: make tests

    - name: Line of Code
      run: make stats

    - name: Bench
      run: go test -bench .

  integration:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start docker-compose.dev.yml
        run: |
          docker-compose -f docker-compose.dev.yml up -d

      - name: Wait for coredns_gslb to be ready
        run: |
          for i in {1..30}; do
            dig @127.0.0.1 -p 8053 gslb.example.com. A && exit 0
            sleep 2
          done
          echo "coredns_gslb did not become ready in time" >&2
          docker-compose -f docker-compose.dev.yml logs
          exit 1

      - name: Run dig queries
        run: |
          set -e
          dig @127.0.0.1 -p 8053 webapp.gslb.example.com. A | grep -q 'IN\s\+A' || (echo 'A record failed' && exit 1)
          dig @127.0.0.1 -p 8053 webapp-geoip-country.app-x.gslb.example.com. A | grep -q 'IN\s\+A' || (echo 'GeoIP A record failed' && exit 1)
          # Add more dig checks as needed

      - name: Show docker-compose logs on failure
        if: failure()
        run: docker-compose -f docker-compose.dev.yml logs

      - name: Tear down
        if: always()
        run: docker-compose -f docker-compose.dev.yml down -v  