name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        go-version: ['1.23', '1.24']
        
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: make tests

    - name: Line of Code
      run: make stats

    - name: Bench
      run: go test -bench .